package shemes;

import java.awt.Point;
import java.util.ArrayList;

import gui.*;
import components.*;

public class Oper1 {
	public static OR ldMAR,incMAR, mxMDR1, mxMDR0, ldMDR, readm,writem, MDRout, DS1out;
	public static OR ldPC, incPC, PC1out, PC2out, JAPSout;
	public static OR wrGPR, rdGPR, GPRDout, incSP, decSP,SP1out, ldPR, PRout;
	public static GuiScheme gui;
	
	
	public static GuiScheme getGui() {
		return gui;
	}
	public static void gui(){
		gui=new GuiScheme("./src/images/oper-bus i fetch,adr.png");
		ArrayList<ArrayList<Point>> sections=null;
		ArrayList<Point> points=null;
		GuiLine line=null;
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,12));
		points.add(new Point(154,12));
		sections.add(points);
		line=new GuiLine(sections,Counter.T02());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,26));
		points.add(new Point(154,26));
		sections.add(points);
		line=new GuiLine(sections,Counter.T09());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,40));
		points.add(new Point(154,40));
		sections.add(points);
		line=new GuiLine(sections,Counter.T11());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,53));
		points.add(new Point(154,53));
		sections.add(points);
		line=new GuiLine(sections,Counter.T16());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,67));
		points.add(new Point(154,67));
		sections.add(points);
		line=new GuiLine(sections,Counter.T20());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,81));
		points.add(new Point(155,81));
		sections.add(points);
		line=new GuiLine(sections,Counter.T23());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,95));
		points.add(new Point(154,95));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,109));
		points.add(new Point(154,109));
		sections.add(points);
		line=new GuiLine(sections,Counter.T60());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,122));
		points.add(new Point(154,122));
		sections.add(points);
		line=new GuiLine(sections,Counter.T65());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,136));
		points.add(new Point(155,136));
		sections.add(points);
		line=new GuiLine(sections,Counter.T68());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,150));
		points.add(new Point(154,150));
		sections.add(points);
		line=new GuiLine(sections,Counter.T6D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,164));
		points.add(new Point(154,164));
		sections.add(points);
		line=new GuiLine(sections,Counter.T70());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,177));
		points.add(new Point(154,177));
		sections.add(points);
		line=new GuiLine(sections,Counter.T76());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,191));
		points.add(new Point(154,191));
		sections.add(points);
		line=new GuiLine(sections,Counter.T79());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,205));
		points.add(new Point(154,205));
		sections.add(points);
		line=new GuiLine(sections,Counter.T7C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,219));
		points.add(new Point(154,219));
		sections.add(points);
		line=new GuiLine(sections,Counter.T7F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(141,233));
		points.add(new Point(154,233));
		sections.add(points);
		line=new GuiLine(sections,Counter.T8E());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(176,129));
		points.add(new Point(189,129));
		sections.add(points);
		line=new GuiLine(sections,Oper1.ldMAR());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(139,267));
		points.add(new Point(147,267));
		sections.add(points);
		line=new GuiLine(sections,Counter.T28());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(139,277));
		points.add(new Point(147,277));
		sections.add(points);
		line=new GuiLine(sections,Counter.T91());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(167,272));
		points.add(new Point(180,272));
		sections.add(points);
		line=new GuiLine(sections,Oper1.incMAR());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,14));
		points.add(new Point(298,14));
		sections.add(points);
		line=new GuiLine(sections,Counter.T3E());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,28));
		points.add(new Point(299,28));
		sections.add(points);
		line=new GuiLine(sections,Counter.T60());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,41));
		points.add(new Point(300,41));
		sections.add(points);
		line=new GuiLine(sections,Counter.T79());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,55));
		points.add(new Point(298,55));
		sections.add(points);
		line=new GuiLine(sections,Counter.T7F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(321,35));
		points.add(new Point(334,35));
		sections.add(points);
		line=new GuiLine(sections,Oper1.mxMDR1());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,81));
		points.add(new Point(305,81));
		sections.add(points);
		line=new GuiLine(sections,Counter.T38());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,95));
		points.add(new Point(305,95));
		sections.add(points);
		line=new GuiLine(sections,Counter.T41());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,109));
		points.add(new Point(306,109));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,123));
		points.add(new Point(306,123));
		sections.add(points);
		line=new GuiLine(sections,Counter.T76());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,136));
		points.add(new Point(305,136));
		sections.add(points);
		line=new GuiLine(sections,Counter.T7C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(328,116));
		points.add(new Point(340,116));
		sections.add(points);
		line=new GuiLine(sections,Oper1.mxMDR0());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,165));
		points.add(new Point(305,165));
		sections.add(points);
		line=new GuiLine(sections,Counter.T38());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,179));
		points.add(new Point(305,179));
		sections.add(points);
		line=new GuiLine(sections,Counter.T3E());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,193));
		points.add(new Point(305,193));
		sections.add(points);
		line=new GuiLine(sections,Counter.T41());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,207));
		points.add(new Point(305,207));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,220));
		points.add(new Point(306,220));
		sections.add(points);
		line=new GuiLine(sections,Counter.T60());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,234));
		points.add(new Point(306,234));
		sections.add(points);
		line=new GuiLine(sections,Counter.T76());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,248));
		points.add(new Point(305,248));
		sections.add(points);
		line=new GuiLine(sections,Counter.T79());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,262));
		points.add(new Point(305,262));
		sections.add(points);
		line=new GuiLine(sections,Counter.T7C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,276));
		points.add(new Point(305,276));
		sections.add(points);
		line=new GuiLine(sections,Counter.T7F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(328,227));
		points.add(new Point(340,227));
		sections.add(points);
		line=new GuiLine(sections,Oper1.ldMDR());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,10));
		points.add(new Point(455,10));
		sections.add(points);
		line=new GuiLine(sections,Counter.T03());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,24));
		points.add(new Point(455,24));
		sections.add(points);
		line=new GuiLine(sections,Counter.T0A());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,38));
		points.add(new Point(455,38));
		sections.add(points);
		line=new GuiLine(sections,Counter.T12());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,52));
		points.add(new Point(455,52));
		sections.add(points);
		line=new GuiLine(sections,Counter.T17());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,66));
		points.add(new Point(455,66));
		sections.add(points);
		line=new GuiLine(sections,Counter.T24());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,79));
		points.add(new Point(456,79));
		sections.add(points);
		line=new GuiLine(sections,Counter.T66());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,93));
		points.add(new Point(456,93));
		sections.add(points);
		line=new GuiLine(sections,Counter.T69());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,107));
		points.add(new Point(455,107));
		sections.add(points);
		line=new GuiLine(sections,Counter.T6E());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,121));
		points.add(new Point(455,121));
		sections.add(points);
		line=new GuiLine(sections,Counter.T71());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,134));
		points.add(new Point(455,134));
		sections.add(points);
		line=new GuiLine(sections,Counter.T8F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,148));
		points.add(new Point(455,148));
		sections.add(points);
		line=new GuiLine(sections,Counter.T92());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(477,86));
		points.add(new Point(490,86));
		sections.add(points);
		line=new GuiLine(sections,Oper1.readm());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,176));
		points.add(new Point(455,176));
		sections.add(points);
		line=new GuiLine(sections,Counter.T39());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,190));
		points.add(new Point(455,190));
		sections.add(points);
		line=new GuiLine(sections,Counter.T3F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,203));
		points.add(new Point(455,203));
		sections.add(points);
		line=new GuiLine(sections,Counter.T42());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,217));
		points.add(new Point(455,217));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5E());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,231));
		points.add(new Point(456,231));
		sections.add(points);
		line=new GuiLine(sections,Counter.T61());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,245));
		points.add(new Point(456,245));
		sections.add(points);
		line=new GuiLine(sections,Counter.T77());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,258));
		points.add(new Point(455,258));
		sections.add(points);
		line=new GuiLine(sections,Counter.T7A());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,272));
		points.add(new Point(455,272));
		sections.add(points);
		line=new GuiLine(sections,Counter.T7D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(442,286));
		points.add(new Point(455,286));
		sections.add(points);
		line=new GuiLine(sections,Counter.T80());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(477,238));
		points.add(new Point(490,238));
		sections.add(points);
		line=new GuiLine(sections,Oper1.writem());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,19));
		points.add(new Point(583,19));
		sections.add(points);
		line=new GuiLine(sections,Counter.T05());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,33));
		points.add(new Point(583,33));
		sections.add(points);
		line=new GuiLine(sections,Counter.T0C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,47));
		points.add(new Point(583,47));
		sections.add(points);
		line=new GuiLine(sections,Counter.T14());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,60));
		points.add(new Point(583,60));
		sections.add(points);
		line=new GuiLine(sections,Counter.T19());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,74));
		points.add(new Point(583,74));
		sections.add(points);
		line=new GuiLine(sections,Counter.T27());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,88));
		points.add(new Point(583,88));
		sections.add(points);
		line=new GuiLine(sections,Counter.T28());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,102));
		points.add(new Point(584,102));
		sections.add(points);
		line=new GuiLine(sections,Counter.T2B());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,115));
		points.add(new Point(584,115));
		sections.add(points);
		line=new GuiLine(sections,Counter.T68());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,129));
		points.add(new Point(583,129));
		sections.add(points);
		line=new GuiLine(sections,Counter.T6B());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,143));
		points.add(new Point(583,143));
		sections.add(points);
		line=new GuiLine(sections,Counter.T70());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,157));
		points.add(new Point(583,157));
		sections.add(points);
		line=new GuiLine(sections,Counter.T73());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,171));
		points.add(new Point(583,171));
		sections.add(points);
		line=new GuiLine(sections,Counter.T91());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,184));
		points.add(new Point(583,184));
		sections.add(points);
		line=new GuiLine(sections,Counter.T94());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(605,109));
		points.add(new Point(618,109));
		sections.add(points);
		line=new GuiLine(sections,Oper1.MDRout());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(570,207));
		points.add(new Point(612,207));
		sections.add(points);
		line=new GuiLine(sections,Counter.T47());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(571,226));
		points.add(new Point(577,226));
		sections.add(points);
		line=new GuiLine(sections,Counter.T20());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(571,240));
		points.add(new Point(579,240));
		sections.add(points);
		line=new GuiLine(sections,Counter.T23());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(571,254));
		points.add(new Point(577,254));
		sections.add(points);
		line=new GuiLine(sections,Counter.T8E());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(599,240));
		points.add(new Point(612,240));
		sections.add(points);
		line=new GuiLine(sections,Oper1.DS1out());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(147,311));
		points.add(new Point(160,311));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5A());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(147,325));
		points.add(new Point(160,325));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5B());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(147,338));
		points.add(new Point(161,338));
		sections.add(points);
		line=new GuiLine(sections,Counter.T63());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(147,352));
		points.add(new Point(162,352));
		sections.add(points);
		line=new GuiLine(sections,Counter.T74());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(147,366));
		points.add(new Point(160,366));
		sections.add(points);
		line=new GuiLine(sections,Counter.T95());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(183,345));
		points.add(new Point(196,345));
		sections.add(points);
		line=new GuiLine(sections,Oper1.ldPC());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(147,400));
		points.add(new Point(160,400));
		sections.add(points);
		line=new GuiLine(sections,Counter.T02());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(147,414));
		points.add(new Point(161,414));
		sections.add(points);
		line=new GuiLine(sections,Counter.T09());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(147,428));
		points.add(new Point(161,428));
		sections.add(points);
		line=new GuiLine(sections,Counter.T11());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(147,442));
		points.add(new Point(160,442));
		sections.add(points);
		line=new GuiLine(sections,Counter.T16());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(183,421));
		points.add(new Point(196,421));
		sections.add(points);
		line=new GuiLine(sections,Oper1.incPC());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(148,473));
		points.add(new Point(189,473));
		sections.add(points);
		line=new GuiLine(sections,Counter.T05());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(148,499));
		points.add(new Point(188,499));
		sections.add(points);
		line=new GuiLine(sections,Counter.T0C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(147,524));
		points.add(new Point(188,524));
		sections.add(points);
		line=new GuiLine(sections,Counter.T14());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(148,550));
		points.add(new Point(190,550));
		sections.add(points);
		line=new GuiLine(sections,Counter.T19());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(285,313));
		points.add(new Point(298,313));
		sections.add(points);
		line=new GuiLine(sections,Counter.T02());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(285,326));
		points.add(new Point(298,326));
		sections.add(points);
		line=new GuiLine(sections,Counter.T09());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(285,340));
		points.add(new Point(299,340));
		sections.add(points);
		line=new GuiLine(sections,Counter.T11());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(285,354));
		points.add(new Point(299,354));
		sections.add(points);
		line=new GuiLine(sections,Counter.T16());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(285,368));
		points.add(new Point(298,368));
		sections.add(points);
		line=new GuiLine(sections,Counter.T22());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(285,381));
		points.add(new Point(298,381));
		sections.add(points);
		line=new GuiLine(sections,Counter.T59());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(321,347));
		points.add(new Point(333,347));
		sections.add(points);
		line=new GuiLine(sections,Oper1.PC1out());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(290,404));
		points.add(new Point(295,404));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(290,418));
		points.add(new Point(296,418));
		sections.add(points);
		line=new GuiLine(sections,Counter.T60());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(290,432));
		points.add(new Point(296,432));
		sections.add(points);
		line=new GuiLine(sections,Counter.T76());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(290,445));
		points.add(new Point(295,445));
		sections.add(points);
		line=new GuiLine(sections,Counter.T79());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(318,425));
		points.add(new Point(331,425));
		sections.add(points);
		line=new GuiLine(sections,Oper1.PC2out());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,462));
		points.add(new Point(336,462));
		sections.add(points);
		line=new GuiLine(sections,Counter.T59());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(293,481));
		points.add(new Point(337,481));
		sections.add(points);
		line=new GuiLine(sections,Counter.T22());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,504));
		points.add(new Point(337,504));
		sections.add(points);
		line=new GuiLine(sections,Counter.T1F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(292,523));
		points.add(new Point(337,523));
		sections.add(points);
		line=new GuiLine(sections,Counter.T2C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(293,540));
		points.add(new Point(337,540));
		sections.add(points);
		line=new GuiLine(sections,Counter.T83());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(284,562));
		points.add(new Point(292,562));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5B());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(284,572));
		points.add(new Point(292,572));
		sections.add(points);
		line=new GuiLine(sections,Counter.T63());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(313,567));
		points.add(new Point(326,567));
		sections.add(points);
		line=new GuiLine(sections,Oper1.JAPSout());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(441,311));
		points.add(new Point(486,311));
		sections.add(points);
		line=new GuiLine(sections,Counter.T0C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(432,332));
		points.add(new Point(440,332));
		sections.add(points);
		line=new GuiLine(sections,Counter.T3C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(432,342));
		points.add(new Point(440,342));
		sections.add(points);
		line=new GuiLine(sections,Counter.T45());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(461,337));
		points.add(new Point(474,337));
		sections.add(points);
		line=new GuiLine(sections,Oper1.wrGPR());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(433,356));
		points.add(new Point(439,356));
		sections.add(points);
		line=new GuiLine(sections,Counter.T1F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(433,370));
		points.add(new Point(441,370));
		sections.add(points);
		line=new GuiLine(sections,Counter.T1D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(433,384));
		points.add(new Point(439,384));
		sections.add(points);
		line=new GuiLine(sections,Counter.T1E());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(461,370));
		points.add(new Point(474,370));
		sections.add(points);
		line=new GuiLine(sections,Oper1.rdGPR());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(440,397));
		points.add(new Point(485,397));
		sections.add(points);
		line=new GuiLine(sections,Counter.T1F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(432,411));
		points.add(new Point(440,411));
		sections.add(points);
		line=new GuiLine(sections,Counter.T1D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(432,421));
		points.add(new Point(440,421));
		sections.add(points);
		line=new GuiLine(sections,Counter.T1E());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(461,416));
		points.add(new Point(474,416));
		sections.add(points);
		line=new GuiLine(sections,Oper1.GPRDout());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(440,435));
		points.add(new Point(485,435));
		sections.add(points);
		line=new GuiLine(sections,Counter.T47());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(438,451));
		points.add(new Point(451,451));
		sections.add(points);
		line=new GuiLine(sections,Counter.T64());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(438,464));
		points.add(new Point(452,464));
		sections.add(points);
		line=new GuiLine(sections,Counter.T65());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(438,478));
		points.add(new Point(452,478));
		sections.add(points);
		line=new GuiLine(sections,Counter.T6C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(438,492));
		points.add(new Point(451,492));
		sections.add(points);
		line=new GuiLine(sections,Counter.T6D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(473,471));
		points.add(new Point(486,471));
		sections.add(points);
		line=new GuiLine(sections,Oper1.incSP());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(438,515));
		points.add(new Point(451,515));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(438,528));
		points.add(new Point(451,528));
		sections.add(points);
		line=new GuiLine(sections,Counter.T63());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(438,542));
		points.add(new Point(452,542));
		sections.add(points);
		line=new GuiLine(sections,Counter.T76());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(438,556));
		points.add(new Point(452,556));
		sections.add(points);
		line=new GuiLine(sections,Counter.T79());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(438,570));
		points.add(new Point(451,570));
		sections.add(points);
		line=new GuiLine(sections,Counter.T7C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(438,583));
		points.add(new Point(451,583));
		sections.add(points);
		line=new GuiLine(sections,Counter.T7F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(473,549));
		points.add(new Point(486,549));
		sections.add(points);
		line=new GuiLine(sections,Oper1.decSP());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(595,316));
		points.add(new Point(608,316));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(595,330));
		points.add(new Point(608,330));
		sections.add(points);
		line=new GuiLine(sections,Counter.T60());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(595,344));
		points.add(new Point(608,344));
		sections.add(points);
		line=new GuiLine(sections,Counter.T65());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(595,357));
		points.add(new Point(608,357));
		sections.add(points);
		line=new GuiLine(sections,Counter.T68());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(595,371));
		points.add(new Point(609,371));
		sections.add(points);
		line=new GuiLine(sections,Counter.T6D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(595,385));
		points.add(new Point(609,385));
		sections.add(points);
		line=new GuiLine(sections,Counter.T70());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(595,399));
		points.add(new Point(608,399));
		sections.add(points);
		line=new GuiLine(sections,Counter.T76());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(595,412));
		points.add(new Point(608,412));
		sections.add(points);
		line=new GuiLine(sections,Counter.T79());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(595,426));
		points.add(new Point(608,426));
		sections.add(points);
		line=new GuiLine(sections,Counter.T7C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(595,440));
		points.add(new Point(608,440));
		sections.add(points);
		line=new GuiLine(sections,Counter.T7F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(630,378));
		points.add(new Point(643,378));
		sections.add(points);
		line=new GuiLine(sections,Oper1.SP1out());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(597,461));
		points.add(new Point(603,461));
		sections.add(points);
		line=new GuiLine(sections,Counter.T1F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(597,475));
		points.add(new Point(605,475));
		sections.add(points);
		line=new GuiLine(sections,Counter.T22());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(597,488));
		points.add(new Point(603,488));
		sections.add(points);
		line=new GuiLine(sections,Counter.T59());
		gui.addLine(line);
		
		sections=new ArrayList<ArrayList<Point>>();//dodat ovaj blok za ldPR
		points=new ArrayList<Point>();
		points.add(new Point(597,499));
		points.add(new Point(603,499));
		sections.add(points);
		line=new GuiLine(sections,Counter.T8D());
		gui.addLine(line);
		
		
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(625,475));
		points.add(new Point(638,475));
		sections.add(points);
		line=new GuiLine(sections,Oper1.ldPR());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(599,514));
		points.add(new Point(611,514));
		sections.add(points);
		line=new GuiLine(sections,Counter.T20());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(599,527));
		points.add(new Point(612,527));
		sections.add(points);
		line=new GuiLine(sections,Counter.T23());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(599,541));
		points.add(new Point(613,541));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5A());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(599,555));
		points.add(new Point(611,555));
		sections.add(points);
		line=new GuiLine(sections,Counter.T8E());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(634,534));
		points.add(new Point(647,534));
		sections.add(points);
		line=new GuiLine(sections,Oper1.PRout());
		gui.addLine(line);


	}
	public static void init(){
		ldMAR=new OR(17);
		incMAR=new OR();
		mxMDR1=new OR(4);
		mxMDR0=new OR(5);
		ldMDR=new OR(9);
		readm=new OR(11);
		writem=new OR(9);
		MDRout=new OR(13);
		DS1out=new OR(3);
		ldPC=new OR(5);
		incPC=new OR(4);
		PC1out=new OR(6);
		PC2out=new OR(4);
		JAPSout=new OR();
		wrGPR=new OR();
		rdGPR=new OR(3);
		GPRDout=new OR();
		incSP=new OR(4);
		decSP=new OR(6);
		SP1out=new OR(10);
		ldPR=new OR(4);//sad ima 4 a ne 3
		PRout=new OR(4);
	}
	public static void connect(){
		
		//blok bus
		ldMAR.setInputPin(0, Counter.T02());
		ldMAR.setInputPin(1, Counter.T09());
		ldMAR.setInputPin(2, Counter.T11());
		ldMAR.setInputPin(3, Counter.T16());
		ldMAR.setInputPin(4, Counter.T20());
		ldMAR.setInputPin(5, Counter.T23());
		ldMAR.setInputPin(6, Counter.T5D());
		ldMAR.setInputPin(7, Counter.T60());
		ldMAR.setInputPin(8, Counter.T65());
		ldMAR.setInputPin(9, Counter.T68());
		ldMAR.setInputPin(10, Counter.T6D());
		ldMAR.setInputPin(11, Counter.T70());
		ldMAR.setInputPin(12, Counter.T76());
		ldMAR.setInputPin(13, Counter.T79());
		ldMAR.setInputPin(14, Counter.T7C());
		ldMAR.setInputPin(15, Counter.T7F());
		ldMAR.setInputPin(16, Counter.T8E());
		
		incMAR.setInputPin(0, Counter.T28());
		incMAR.setInputPin(1, Counter.T91());
		
		mxMDR1.setInputPin(0, Counter.T3E());
		mxMDR1.setInputPin(1, Counter.T60());
		mxMDR1.setInputPin(2, Counter.T79());
		mxMDR1.setInputPin(3, Counter.T7F());
		
		mxMDR0.setInputPin(0, Counter.T38());
		mxMDR0.setInputPin(1, Counter.T41());
		mxMDR0.setInputPin(2, Counter.T5D());
		mxMDR0.setInputPin(3, Counter.T76());
		mxMDR0.setInputPin(4, Counter.T7C());
		
		ldMDR.setInputPin(0, Counter.T38());
		ldMDR.setInputPin(1, Counter.T3E());
		ldMDR.setInputPin(2, Counter.T41());
		ldMDR.setInputPin(3, Counter.T5D());
		ldMDR.setInputPin(4, Counter.T60());
		ldMDR.setInputPin(5, Counter.T76());
		ldMDR.setInputPin(6, Counter.T79());
		ldMDR.setInputPin(7, Counter.T7C());
		ldMDR.setInputPin(8, Counter.T7F());
		
		readm.setInputPin(0, Counter.T03());
		readm.setInputPin(1, Counter.T0A());
		readm.setInputPin(2, Counter.T12());
		readm.setInputPin(3, Counter.T17());
		readm.setInputPin(4, Counter.T24());
		readm.setInputPin(5, Counter.T66());
		readm.setInputPin(6, Counter.T69());
		readm.setInputPin(7, Counter.T6E());
		readm.setInputPin(8, Counter.T71());
		readm.setInputPin(9, Counter.T8F());
		readm.setInputPin(10, Counter.T92());
		
		writem.setInputPin(0, Counter.T39());
		writem.setInputPin(1, Counter.T3F());
		writem.setInputPin(2, Counter.T42());
		writem.setInputPin(3, Counter.T5E());
		writem.setInputPin(4, Counter.T61());
		writem.setInputPin(5, Counter.T77());
		writem.setInputPin(6, Counter.T7A());
		writem.setInputPin(7, Counter.T7D());
		writem.setInputPin(8, Counter.T80());
		
		MDRout.setInputPin(0, Counter.T05());
		MDRout.setInputPin(1, Counter.T0C());
		MDRout.setInputPin(2, Counter.T14());
		MDRout.setInputPin(3, Counter.T19());
		MDRout.setInputPin(4, Counter.T27());
		MDRout.setInputPin(5, Counter.T28());
		MDRout.setInputPin(6, Counter.T2B());
		MDRout.setInputPin(7, Counter.T68());
		MDRout.setInputPin(8, Counter.T6B());
		MDRout.setInputPin(9, Counter.T70());
		MDRout.setInputPin(10, Counter.T73());
		MDRout.setInputPin(11, Counter.T91());
		MDRout.setInputPin(12, Counter.T94());
		
		DS1out.setInputPin(0, Counter.T20());
		DS1out.setInputPin(1, Counter.T23());
		DS1out.setInputPin(2, Counter.T8E());
		
		//blok fetch
		ldPC.setInputPin(0, Counter.T5A());
		ldPC.setInputPin(1, Counter.T5B());
		ldPC.setInputPin(2, Counter.T63());
		ldPC.setInputPin(3, Counter.T74());
		ldPC.setInputPin(4, Counter.T95());
		
		incPC.setInputPin(0, Counter.T02());
		incPC.setInputPin(1, Counter.T09());
		incPC.setInputPin(2, Counter.T11());
		incPC.setInputPin(3, Counter.T16());
		
		PC1out.setInputPin(0, Counter.T02());
		PC1out.setInputPin(1, Counter.T09());
		PC1out.setInputPin(2, Counter.T11());
		PC1out.setInputPin(3, Counter.T16());
		PC1out.setInputPin(4, Counter.T22());
		PC1out.setInputPin(5, Counter.T59());
		
		PC2out.setInputPin(0, Counter.T5D());
		PC2out.setInputPin(1, Counter.T60());
		PC2out.setInputPin(2, Counter.T76());
		PC2out.setInputPin(3, Counter.T79());
		
		JAPSout.setInputPin(0, Counter.T5B());
		JAPSout.setInputPin(1, Counter.T63());
		
		wrGPR.setInputPin(0, Counter.T3C());
		wrGPR.setInputPin(1, Counter.T45());
		
		rdGPR.setInputPin(0, Counter.T1F());
		rdGPR.setInputPin(1, Counter.T1D());
		rdGPR.setInputPin(2, Counter.T1E());
		
		GPRDout.setInputPin(0, Counter.T1D());
		GPRDout.setInputPin(1, Counter.T1E());
		
		incSP.setInputPin(0, Counter.T64());
		incSP.setInputPin(1, Counter.T65());
		incSP.setInputPin(2, Counter.T6C());
		incSP.setInputPin(3, Counter.T6D());
		
		decSP.setInputPin(0, Counter.T5D());
		decSP.setInputPin(1, Counter.T63());
		decSP.setInputPin(2, Counter.T76());
		decSP.setInputPin(3, Counter.T79());
		decSP.setInputPin(4, Counter.T7C());
		decSP.setInputPin(5, Counter.T7F());
		
		SP1out.setInputPin(0, Counter.T5D());
		SP1out.setInputPin(1, Counter.T60());
		SP1out.setInputPin(2, Counter.T65());
		SP1out.setInputPin(3, Counter.T68());
		SP1out.setInputPin(4, Counter.T6D());
		SP1out.setInputPin(5, Counter.T70());
		SP1out.setInputPin(6, Counter.T76());
		SP1out.setInputPin(7, Counter.T79());
		SP1out.setInputPin(8, Counter.T7C());
		SP1out.setInputPin(9, Counter.T7F());
		

		ldPR.setInputPin(0, Counter.T1F());
		ldPR.setInputPin(1, Counter.T22());
		ldPR.setInputPin(2, Counter.T59());
		ldPR.setInputPin(3, Counter.T8D());
		
		PRout.setInputPin(0, Counter.T20());
		PRout.setInputPin(1, Counter.T23());
		PRout.setInputPin(2, Counter.T5A());
		PRout.setInputPin(3, Counter.T8E());
		
	}
	
	public static Pin ldMAR(){
		return ldMAR.getOut(0);	
	}
	public static Pin incMAR(){
		return incMAR.getOut(0);	
	}
	public static Pin mxMDR1(){
		return mxMDR1.getOut(0);	
	}
	public static Pin mxMDR0(){
		return mxMDR0.getOut(0);	
	}
	public static Pin ldMDR(){
		return ldMDR.getOut(0);	
	}
	public static Pin readm(){
		return readm.getOut(0);	
	}
	public static Pin writem(){
		return writem.getOut(0);	
	}
	public static Pin MDRout(){
		return MDRout.getOut(0);	
	}
	public static Pin S2Dout(){
		return Counter.T47();	
	}
	public static Pin DS1out(){
		return DS1out.getOut(0);	
	}
	public static Pin ldPC(){
		return ldPC.getOut(0);	
	}
	public static Pin incPC(){
		return incPC.getOut(0);	
	}
	public static Pin ldIR0(){
		return Counter.T05();	
	}
	public static Pin ldIR1(){
		return Counter.T0C();	
	}
	public static Pin ldIR2(){
		return Counter.T14();	
	}
	public static Pin ldIR3(){
		return Counter.T19();	
	}
	public static Pin PC1out(){
		return PC1out.getOut(0);	
	}
	public static Pin PC2out(){
		return PC2out.getOut(0);	
	}
	public static Pin JDISPout(){
		return Counter.T59();	
	}
	public static Pin INTENTRYout(){
		return Counter.T83();	
	}
	public static Pin PCRDISPout(){
		return Counter.T22();	
	}
	public static Pin REGIDISPout(){
		return Counter.T1F();	
	}
	public static Pin IMMout(){
		return Counter.T2C();	
	}
	public static Pin JAPSout(){
		return JAPSout.getOut(0);	
	}
	public static Pin ldGPRAR(){
		return Counter.T0C();	
	}
	public static Pin wrGPR(){
		return wrGPR.getOut(0);	
	}
	public static Pin rdGPR(){
		return rdGPR.getOut(0);	
	}
	public static Pin GPR1out(){
		return Counter.T1F();	
	}
	public static Pin GPRDout(){
		return GPRDout.getOut(0);	
	}
	public static Pin ldSP(){
		return Counter.T47();	
	}
	public static Pin incSP(){
		return incSP.getOut(0);	
	}
	public static Pin decSP(){
		return decSP.getOut(0);	
	}
	public static Pin SP1out(){
		return SP1out.getOut(0);	
	}
	public static Pin ldPR(){
		return ldPR.getOut(0);	
	}
	public static Pin PRout(){
		return PRout.getOut(0);	
	}

}
