package shemes;

import java.awt.Point;
import java.util.ArrayList;

import gui.GuiLine;
import gui.GuiScheme;
import components.*;

public class Uprav1 {
	public static AND AND1, AND2, AND3, AND4, AND5, AND6, AND7, AND8, AND9, AND10;
	public static AND AND11, AND12, AND13, AND14, AND15, AND16, AND17, AND18, AND19;
	public static OR bruncnd, brcnd, brnotbrqstop, brstore, brLDW, brregdir;
	public static NOT NOT1, NOT2, NOT3, NOT4, NOT5, NOT6, NOT7, NOT8, NOT9, NOT10;
	public static AND ANDbrqstart;
	public static NOT NOTBRQSTOP;
	public static GuiScheme gui;

	public static GuiScheme getGui() {
		return gui;
	}
	public static void gui(){
		gui=new GuiScheme("./src/images/uprav-uslovi.png");
		ArrayList<ArrayList<Point>> sections=null;
		ArrayList<Point> points=null;
		GuiLine line=null;
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(111,10));
		points.add(new Point(156,10));
		sections.add(points);
		line=new GuiLine(sections,Counter.T1A());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(111,32));
		points.add(new Point(156,32));
		sections.add(points);
		line=new GuiLine(sections,Counter.T2D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,51));
		points.add(new Point(121,51));
		sections.add(points);
		line=new GuiLine(sections,Counter.T07());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,65));
		points.add(new Point(121,65));
		sections.add(points);
		line=new GuiLine(sections,Counter.T0E());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,78));
		points.add(new Point(121,78));
		sections.add(points);
		line=new GuiLine(sections,Counter.T1D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,91));
		points.add(new Point(121,91));
		sections.add(points);
		line=new GuiLine(sections,Counter.T1E());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,104));
		points.add(new Point(121,104));
		sections.add(points);
		line=new GuiLine(sections,Counter.T21());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,118));
		points.add(new Point(121,118));
		sections.add(points);
		line=new GuiLine(sections,Counter.T27());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,132));
		points.add(new Point(121,132));
		sections.add(points);
		line=new GuiLine(sections,Counter.T2B());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,145));
		points.add(new Point(121,145));
		sections.add(points);
		line=new GuiLine(sections,Counter.T2E());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,159));
		points.add(new Point(121,159));
		sections.add(points);
		line=new GuiLine(sections,Counter.T2F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,172));
		points.add(new Point(121,172));
		sections.add(points);
		line=new GuiLine(sections,Counter.T30());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,186));
		points.add(new Point(121,186));
		sections.add(points);
		line=new GuiLine(sections,Counter.T31());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,200));
		points.add(new Point(121,200));
		sections.add(points);
		line=new GuiLine(sections,Counter.T32());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,213));
		points.add(new Point(121,213));
		sections.add(points);
		line=new GuiLine(sections,Counter.T33());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,227));
		points.add(new Point(121,227));
		sections.add(points);
		line=new GuiLine(sections,Counter.T35());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,240));
		points.add(new Point(121,240));
		sections.add(points);
		line=new GuiLine(sections,Counter.T36());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,254));
		points.add(new Point(121,254));
		sections.add(points);
		line=new GuiLine(sections,Counter.T3B());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,267));
		points.add(new Point(121,267));
		sections.add(points);
		line=new GuiLine(sections,Counter.T3C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,281));
		points.add(new Point(121,281));
		sections.add(points);
		line=new GuiLine(sections,Counter.T44());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,295));
		points.add(new Point(121,295));
		sections.add(points);
		line=new GuiLine(sections,Counter.T45());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,308));
		points.add(new Point(122,308));
		sections.add(points);
		line=new GuiLine(sections,Counter.T46());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,322));
		points.add(new Point(122,322));
		sections.add(points);
		line=new GuiLine(sections,Counter.T47());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,337));
		points.add(new Point(121,337));
		sections.add(points);
		line=new GuiLine(sections,Counter.T49());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,351));
		points.add(new Point(121,351));
		sections.add(points);
		line=new GuiLine(sections,Counter.T4B());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,364));
		points.add(new Point(121,364));
		sections.add(points);
		line=new GuiLine(sections,Counter.T4D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,377));
		points.add(new Point(121,377));
		sections.add(points);
		line=new GuiLine(sections,Counter.T4F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,391));
		points.add(new Point(121,391));
		sections.add(points);
		line=new GuiLine(sections,Counter.T51());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,404));
		points.add(new Point(121,404));
		sections.add(points);
		line=new GuiLine(sections,Counter.T53());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,418));
		points.add(new Point(121,418));
		sections.add(points);
		line=new GuiLine(sections,Counter.T55());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,431));
		points.add(new Point(121,431));
		sections.add(points);
		line=new GuiLine(sections,Counter.T57());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,445));
		points.add(new Point(121,445));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5A());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(109,458));
		points.add(new Point(121,458));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5B());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,472));
		points.add(new Point(121,472));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,486));
		points.add(new Point(121,486));
		sections.add(points);
		line=new GuiLine(sections,Counter.T63());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,499));
		points.add(new Point(121,499));
		sections.add(points);
		line=new GuiLine(sections,Counter.T83());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,513));
		points.add(new Point(121,513));
		sections.add(points);
		line=new GuiLine(sections,Counter.T85());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,526));
		points.add(new Point(121,526));
		sections.add(points);
		line=new GuiLine(sections,Counter.T87());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,540));
		points.add(new Point(121,540));
		sections.add(points);
		line=new GuiLine(sections,Counter.T89());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,554));
		points.add(new Point(121,554));
		sections.add(points);
		line=new GuiLine(sections,Counter.T8B());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(108,567));
		points.add(new Point(121,567));
		sections.add(points);
		line=new GuiLine(sections,Counter.T95());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(143,315));
		points.add(new Point(156,315));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.bruncnd());
		gui.addLine(line);
		
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,20));
		points.add(new Point(289,20));
		sections.add(points);
		line=new GuiLine(sections,Counter.T00());
		gui.addLine(line);
		
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,32));
		points.add(new Point(286,32));
		sections.add(points);
		line=new GuiLine(sections,Exec2.START());
		gui.addLine(line);
		
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,46));
		points.add(new Point(289,46));
		sections.add(points);
		line=new GuiLine(sections,Counter.T01());
		gui.addLine(line);
		
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,58));
		points.add(new Point(289,58));
		sections.add(points);
		line=new GuiLine(sections,Bus2.brqstart());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,72));
		points.add(new Point(289,72));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.brnotbrqstop());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,84));
		points.add(new Point(286,84));
		sections.add(points);
		line=new GuiLine(sections,Bus3.brqstop());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,98));
		points.add(new Point(290,98));
		sections.add(points);
		line=new GuiLine(sections,Counter.T06());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,110));
		points.add(new Point(286,110));
		sections.add(points);
		line=new GuiLine(sections,Fetch3.gropr());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,123));
		points.add(new Point(290,123));
		sections.add(points);
		line=new GuiLine(sections,Counter.T08());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,135));
		points.add(new Point(290,135));
		sections.add(points);
		line=new GuiLine(sections,Fetch3.I1());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,148));
		points.add(new Point(290,148));
		sections.add(points);
		line=new GuiLine(sections,Counter.T0D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,161));
		points.add(new Point(286,161));
		sections.add(points);
		line=new GuiLine(sections,Fetch3.gradr());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,174));
		points.add(new Point(290,174));
		sections.add(points);
		line=new GuiLine(sections,Counter.T0F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,186));
		points.add(new Point(290,186));
		sections.add(points);
		line=new GuiLine(sections,Fetch3.I2_brnch());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,199));
		points.add(new Point(290,199));
		sections.add(points);
		line=new GuiLine(sections,Counter.T10());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,212));
		points.add(new Point(290,212));
		sections.add(points);
		line=new GuiLine(sections,Fetch3.I2_arlog());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,225));
		points.add(new Point(290,225));
		sections.add(points);
		line=new GuiLine(sections,Counter.T14());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,237));
		points.add(new Point(290,237));
		sections.add(points);
		line=new GuiLine(sections,Fetch3.I3_jump());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,250));
		points.add(new Point(290,250));
		sections.add(points);
		line=new GuiLine(sections,Counter.T15());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,263));
		points.add(new Point(290,263));
		sections.add(points);
		line=new GuiLine(sections,Fetch3.I3_arlog());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,276));
		points.add(new Point(290,276));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.brstore());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,288));
		points.add(new Point(290,288));
		sections.add(points);
		line=new GuiLine(sections,Fetch3.store());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,301));
		points.add(new Point(290,301));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.brLDW());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,314));
		points.add(new Point(290,314));
		sections.add(points);
		line=new GuiLine(sections,Fetch2.LDW());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,327));
		points.add(new Point(290,327));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.brregdir());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,339));
		points.add(new Point(290,339));
		sections.add(points);
		line=new GuiLine(sections,Fetch2.regdir());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,351));
		points.add(new Point(290,351));
		sections.add(points);
		line=new GuiLine(sections,Counter.T58());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,364));
		points.add(new Point(286,364));
		sections.add(points);
		line=new GuiLine(sections,Exec4.brpom());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,377));
		points.add(new Point(290,377));
		sections.add(points);
		line=new GuiLine(sections,Counter.T75());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,389));
		points.add(new Point(286,389));
		sections.add(points);
		line=new GuiLine(sections,Intr1 .prekid());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,402));
		points.add(new Point(290,402));
		sections.add(points);
		line=new GuiLine(sections,Counter.T82());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,415));
		points.add(new Point(286,415));
		sections.add(points);
		line=new GuiLine(sections,Intr1.PRINS());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,430));
		points.add(new Point(290,430));
		sections.add(points);
		line=new GuiLine(sections,Counter.T84());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,443));
		points.add(new Point(286,443));
		sections.add(points);
		line=new GuiLine(sections,Intr1.PRCOD());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,456));
		points.add(new Point(290,456));
		sections.add(points);
		line=new GuiLine(sections,Counter.T86());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,468));
		points.add(new Point(286,468));
		sections.add(points);
		line=new GuiLine(sections,Intr1.PRADR());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,485));
		points.add(new Point(290,485));
		sections.add(points);
		line=new GuiLine(sections,Counter.T88());
		gui.addLine(line); 
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,497));
		points.add(new Point(286,497));
		sections.add(points);
		line=new GuiLine(sections,Intr1.PRINM());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,510));
		points.add(new Point(290,510));
		sections.add(points);
		line=new GuiLine(sections,Counter.T8A());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(277,522));
		points.add(new Point(286,522));
		sections.add(points);
		line=new GuiLine(sections,Intr2.printr());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(381,269));
		points.add(new Point(394,269));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.brcnd());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,26));
		points.add(new Point(359,26));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND1.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,51));
		points.add(new Point(359,51));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.ANDbrqstart.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,78));
		points.add(new Point(359,78));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND2.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,103));
		points.add(new Point(359,103));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND3.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,129));
		points.add(new Point(359,129));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND4.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,154));
		points.add(new Point(359,154));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND5.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,180));
		points.add(new Point(359,180));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND6.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,205));
		points.add(new Point(359,205));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND7.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,231));
		points.add(new Point(359,231));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND8.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,256));
		points.add(new Point(359,256));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND9.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,282));
		points.add(new Point(359,282));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND10.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,307));
		points.add(new Point(359,307));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND11.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,333));
		points.add(new Point(359,333));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND12.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,357));
		points.add(new Point(359,357));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND13.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,383));
		points.add(new Point(359,383));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND14.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,408));
		points.add(new Point(359,408));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND15.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,436));
		points.add(new Point(359,436));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND16.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,462));
		points.add(new Point(359,462));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND17.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,490));
		points.add(new Point(359,490));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND18.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(312,516));
		points.add(new Point(359,516));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.AND19.getOut(0));
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(247,545));
		points.add(new Point(291,545));
		sections.add(points);
		line=new GuiLine(sections,Counter.T00());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(247,565));
		points.add(new Point(291,565));
		sections.add(points);
		line=new GuiLine(sections,Counter.T01());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,13));
		points.add(new Point(499,13));
		sections.add(points);
		line=new GuiLine(sections,Counter.T04());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,27));
		points.add(new Point(499,27));
		sections.add(points);
		line=new GuiLine(sections,Counter.T0B());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,40));
		points.add(new Point(499,40));
		sections.add(points);
		line=new GuiLine(sections,Counter.T13());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,54));
		points.add(new Point(499,54));
		sections.add(points);
		line=new GuiLine(sections,Counter.T18());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,68));
		points.add(new Point(499,68));
		sections.add(points);
		line=new GuiLine(sections,Counter.T25());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,81));
		points.add(new Point(499,81));
		sections.add(points);
		line=new GuiLine(sections,Counter.T2A());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,95));
		points.add(new Point(499,95));
		sections.add(points);
		line=new GuiLine(sections,Counter.T3A());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,108));
		points.add(new Point(499,108));
		sections.add(points);
		line=new GuiLine(sections,Counter.T40());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,122));
		points.add(new Point(499,122));
		sections.add(points);
		line=new GuiLine(sections,Counter.T43());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,135));
		points.add(new Point(499,135));
		sections.add(points);
		line=new GuiLine(sections,Counter.T5F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,149));
		points.add(new Point(500,149));
		sections.add(points);
		line=new GuiLine(sections,Counter.T62());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,164));
		points.add(new Point(499,164));
		sections.add(points);
		line=new GuiLine(sections,Counter.T67());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,178));
		points.add(new Point(499,178));
		sections.add(points);
		line=new GuiLine(sections,Counter.T6A());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,191));
		points.add(new Point(499,191));
		sections.add(points);
		line=new GuiLine(sections,Counter.T6F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,204));
		points.add(new Point(499,204));
		sections.add(points);
		line=new GuiLine(sections,Counter.T72());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,218));
		points.add(new Point(499,218));
		sections.add(points);
		line=new GuiLine(sections,Counter.T78());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,231));
		points.add(new Point(499,231));
		sections.add(points);
		line=new GuiLine(sections,Counter.T78());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,245));
		points.add(new Point(499,245));
		sections.add(points);
		line=new GuiLine(sections,Counter.T7E());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,259));
		points.add(new Point(499,259));
		sections.add(points);
		line=new GuiLine(sections,Counter.T81());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,272));
		points.add(new Point(499,272));
		sections.add(points);
		line=new GuiLine(sections,Counter.T90());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(486,286));
		points.add(new Point(499,286));
		sections.add(points);
		line=new GuiLine(sections,Counter.T93());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(521,142));
		points.add(new Point(533,142));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.brnotbrqstop());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(578,175));
		points.add(new Point(622,175));
		sections.add(points);
		line=new GuiLine(sections,Counter.T58());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(578,197));
		points.add(new Point(622,197));
		sections.add(points);
		line=new GuiLine(sections,Counter.T75());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(578,218));
		points.add(new Point(622,218));
		sections.add(points);
		line=new GuiLine(sections,Counter.T82());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(578,240));
		points.add(new Point(622,240));
		sections.add(points);
		line=new GuiLine(sections,Counter.T84());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(578,264));
		points.add(new Point(622,264));
		sections.add(points);
		line=new GuiLine(sections,Counter.T86());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(578,286));
		points.add(new Point(622,286));
		sections.add(points);
		line=new GuiLine(sections,Counter.T88());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(578,306));
		points.add(new Point(622,306));
		sections.add(points);
		line=new GuiLine(sections,Counter.T8A());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(490,339));
		points.add(new Point(534,339));
		sections.add(points);
		line=new GuiLine(sections,Counter.T06());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(490,361));
		points.add(new Point(534,361));
		sections.add(points);
		line=new GuiLine(sections,Counter.T08());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(490,382));
		points.add(new Point(534,382));
		sections.add(points);
		line=new GuiLine(sections,Counter.T0D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(534,404));
		points.add(new Point(490,404));
		sections.add(points);
		line=new GuiLine(sections,Counter.T0F());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(490,427));
		points.add(new Point(534,427));
		sections.add(points);
		line=new GuiLine(sections,Counter.T10());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(490,450));
		points.add(new Point(534,450));
		sections.add(points);
		line=new GuiLine(sections,Counter.T14());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(490,470));
		points.add(new Point(534,470));
		sections.add(points);
		line=new GuiLine(sections,Counter.T15());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(489,490));
		points.add(new Point(495,490));
		sections.add(points);
		line=new GuiLine(sections,Counter.T1B());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(489,504));
		points.add(new Point(497,504));
		sections.add(points);
		line=new GuiLine(sections,Counter.T20());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(489,518));
		points.add(new Point(495,518));
		sections.add(points);
		line=new GuiLine(sections,Counter.T23());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(517,504));
		points.add(new Point(530,504));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.brstore());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(484,537));
		points.add(new Point(492,537));
		sections.add(points);
		line=new GuiLine(sections,Counter.T1C());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(484,547));
		points.add(new Point(492,547));
		sections.add(points);
		line=new GuiLine(sections,Counter.T26());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(512,542));
		points.add(new Point(525,542));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.brLDW());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(484,569));
		points.add(new Point(492,569));
		sections.add(points);
		line=new GuiLine(sections,Counter.T37());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(484,579));
		points.add(new Point(492,579));
		sections.add(points);
		line=new GuiLine(sections,Counter.T3D());
		gui.addLine(line);
		sections=new ArrayList<ArrayList<Point>>();
		points=new ArrayList<Point>();
		points.add(new Point(512,574));
		points.add(new Point(525,574));
		sections.add(points);
		line=new GuiLine(sections,Uprav1.brregdir());
		gui.addLine(line);

	}
	public static void init(){
		AND1 = new AND();
		AND2 = new AND();
		AND3 = new AND();
		AND4 = new AND();
		AND5 = new AND();
		AND6 = new AND();
		AND7 = new AND();
		AND8 = new AND();
		AND9 = new AND();
		AND10 = new AND();
		AND11 = new AND();
		AND12 = new AND();
		AND13 = new AND();
		AND14 = new AND();
		AND15 = new AND();
		AND16 = new AND();
		AND17 = new AND();
		AND18 = new AND();
		AND19 = new AND();
		bruncnd = new OR(39);
		brcnd = new OR(20);//za 1 vise
		brnotbrqstop = new OR(21);//za 1 manje
		brstore = new OR(3);
		brLDW = new OR();
		brregdir = new OR();
		NOT1 = new NOT();
		NOT2 = new NOT();
		NOT3 = new NOT();
		NOT4 = new NOT();
		NOT5 = new NOT();
		NOT6 = new NOT();
		NOT7 = new NOT();
		NOT8 = new NOT();
		NOT9 = new NOT();
		NOT10 = new NOT();
		
		ANDbrqstart=new AND();//ide u brcnd
		NOTBRQSTOP=new NOT();
	}
	public static void connect(){
		bruncnd.setInputPin(0, Counter.T07());
		bruncnd.setInputPin(1, Counter.T0E());
		bruncnd.setInputPin(2, Counter.T1D());
		bruncnd.setInputPin(3, Counter.T1E());
		bruncnd.setInputPin(4, Counter.T21());
		bruncnd.setInputPin(5, Counter.T27());
		bruncnd.setInputPin(6, Counter.T2B());
		bruncnd.setInputPin(7, Counter.T2E());
		bruncnd.setInputPin(8, Counter.T2F());
		bruncnd.setInputPin(9, Counter.T30());
		bruncnd.setInputPin(10, Counter.T31());
		bruncnd.setInputPin(11, Counter.T32());
		bruncnd.setInputPin(12, Counter.T33());
		bruncnd.setInputPin(13, Counter.T35());
		bruncnd.setInputPin(14, Counter.T36());
		bruncnd.setInputPin(15, Counter.T3B());
		bruncnd.setInputPin(16, Counter.T3C());
		bruncnd.setInputPin(17, Counter.T44());
		bruncnd.setInputPin(18, Counter.T45());
		bruncnd.setInputPin(19, Counter.T46());
		bruncnd.setInputPin(20, Counter.T47());
		bruncnd.setInputPin(21, Counter.T49());
		bruncnd.setInputPin(22, Counter.T4B());
		bruncnd.setInputPin(23, Counter.T4D());
		bruncnd.setInputPin(24, Counter.T4F());
		bruncnd.setInputPin(25, Counter.T51());
		bruncnd.setInputPin(26, Counter.T53());
		bruncnd.setInputPin(27, Counter.T55());
		bruncnd.setInputPin(28, Counter.T57());
		bruncnd.setInputPin(29, Counter.T5A());
		bruncnd.setInputPin(30, Counter.T5B());
		bruncnd.setInputPin(31, Counter.T5C());
		bruncnd.setInputPin(32, Counter.T63());
		bruncnd.setInputPin(33, Counter.T83());
		bruncnd.setInputPin(34, Counter.T85());
		bruncnd.setInputPin(35, Counter.T87());
		bruncnd.setInputPin(36, Counter.T89());
		bruncnd.setInputPin(37, Counter.T8B());
		bruncnd.setInputPin(38, Counter.T95());
		
		NOT1.setInputPin(0,Exec2.START());	
		AND1.setInputPin(0, Counter.T00());//brnotSTART=T00
		AND1.setInputPin(1, NOT1.getOut(0));
		brcnd.setInputPin(0, AND1.getOut(0));
		
		NOTBRQSTOP.setInputPin(0, Bus3.brqstop());															//BRBRqstopDODATO  dodato
		AND2.setInputPin(0, brnotbrqstop.getOut(0));
		AND2.setInputPin(1,NOTBRQSTOP.getOut(0));
		brcnd.setInputPin(1, AND2.getOut(0));
		
		NOT2.setInputPin(0,Fetch3.gropr());	
		AND3.setInputPin(0, Counter.T06());//brnotgropr=T06
		AND3.setInputPin(1, NOT2.getOut(0));
		brcnd.setInputPin(2, AND3.getOut(0));
		
		AND4.setInputPin(0, Counter.T08());//brI1=T08
		AND4.setInputPin(1, Fetch3.I1());
		brcnd.setInputPin(3, AND4.getOut(0));
		
		NOT3.setInputPin(0,Fetch3.gradr());	
		AND5.setInputPin(0, Counter.T0D());//brnotgradr=T0D
		AND5.setInputPin(1, NOT3.getOut(0));
		brcnd.setInputPin(4, AND5.getOut(0));
		
		AND6.setInputPin(0, Counter.T0F());//brI2_brnc=T0F
		AND6.setInputPin(1, Fetch3.I2_brnch());
		brcnd.setInputPin(5, AND6.getOut(0));
		
		AND7.setInputPin(0, Counter.T10());//brI2_arlog=T10
		AND7.setInputPin(1, Fetch3.I2_arlog());
		brcnd.setInputPin(6, AND7.getOut(0));
		
		AND8.setInputPin(0, Counter.T14());//brI3_jump=T14
		AND8.setInputPin(1, Fetch3.I3_jump());
		brcnd.setInputPin(7, AND8.getOut(0));
		
		AND9.setInputPin(0, Counter.T15());//brI3_arlog=T15
		AND9.setInputPin(1, Fetch3.I3_arlog());
		brcnd.setInputPin(8, AND9.getOut(0));
		
		AND10.setInputPin(0, brstore.getOut(0));
		AND10.setInputPin(1, Fetch3.store());
		brcnd.setInputPin(9, AND10.getOut(0));
		
		AND11.setInputPin(0, brLDW.getOut(0));
		AND11.setInputPin(1, Fetch2.LDW());
		brcnd.setInputPin(10, AND11.getOut(0));
		
		AND12.setInputPin(0, brregdir.getOut(0));
		AND12.setInputPin(1, Fetch2.regdir());
		brcnd.setInputPin(11, AND12.getOut(0));
		
		NOT4.setInputPin(0,Exec4.brpom());	
		AND13.setInputPin(0, Counter.T58());//brnotpom=T58
		AND13.setInputPin(1, NOT4.getOut(0));
		brcnd.setInputPin(12, AND13.getOut(0));
		
		NOT5.setInputPin(0,Intr1.prekid());	
		AND14.setInputPin(0, Counter.T75());//brnotprekid=T75
		AND14.setInputPin(1, NOT5.getOut(0));
		brcnd.setInputPin(13, AND14.getOut(0));
		
		NOT6.setInputPin(0,Intr1.PRINS());	
		AND15.setInputPin(0, Counter.T82());//brnotPRINS=T82
		AND15.setInputPin(1, NOT6.getOut(0));
		brcnd.setInputPin(14, AND15.getOut(0));
		
		NOT7.setInputPin(0,Intr1.PRCOD());	
		AND16.setInputPin(0, Counter.T84());//brnotPRCOD=T84
		AND16.setInputPin(1, NOT7.getOut(0));
		brcnd.setInputPin(15, AND16.getOut(0));
		
		NOT8.setInputPin(0,Intr1.PRADR());	
		AND17.setInputPin(0, Counter.T86());//brnotPRADR=T75
		AND17.setInputPin(1, NOT8.getOut(0));
		brcnd.setInputPin(16, AND17.getOut(0));
		
		NOT9.setInputPin(0,Intr1.PRINM());	
		AND18.setInputPin(0, Counter.T88());//brnotPRINM=T78
		AND18.setInputPin(1, NOT9.getOut(0));
		brcnd.setInputPin(17, AND18.getOut(0));
		
		NOT10.setInputPin(0,Intr2.printr());	
		AND19.setInputPin(0, Counter.T86());//brnotprintr=T8A
		AND19.setInputPin(1, NOT10.getOut(0));
		brcnd.setInputPin(18, AND19.getOut(0));
		
		ANDbrqstart.setInputPin(0,Counter.T01());
		ANDbrqstart.setInputPin(1,Bus2.brqstart());
		brcnd.setInputPin(19, ANDbrqstart.getOut(0));
		
		//brnotNFC.setInputPin(0, Counter.T01());
		brnotbrqstop.setInputPin(0, Counter.T04());
		brnotbrqstop.setInputPin(1, Counter.T0B());
		brnotbrqstop.setInputPin(2, Counter.T13());
		brnotbrqstop.setInputPin(3, Counter.T18());
		brnotbrqstop.setInputPin(4, Counter.T25());
		brnotbrqstop.setInputPin(5, Counter.T2A());
		brnotbrqstop.setInputPin(6, Counter.T3A());
		brnotbrqstop.setInputPin(7, Counter.T40());
		brnotbrqstop.setInputPin(8, Counter.T43());
		brnotbrqstop.setInputPin(9, Counter.T5F());
		brnotbrqstop.setInputPin(10, Counter.T62());
		brnotbrqstop.setInputPin(11, Counter.T67());
		brnotbrqstop.setInputPin(12, Counter.T6A());
		brnotbrqstop.setInputPin(13, Counter.T6F());
		brnotbrqstop.setInputPin(14, Counter.T72());
		brnotbrqstop.setInputPin(15, Counter.T78());
		brnotbrqstop.setInputPin(16, Counter.T7B());
		brnotbrqstop.setInputPin(17, Counter.T7E());
		brnotbrqstop.setInputPin(18, Counter.T81());
		brnotbrqstop.setInputPin(19, Counter.T90());
		brnotbrqstop.setInputPin(20, Counter.T93());
		
		brstore.setInputPin(0, Counter.T20());
		brstore.setInputPin(1, Counter.T23());
		brstore.setInputPin(2, Counter.T1B());
		
		brLDW.setInputPin(0, Counter.T1C());
		brLDW.setInputPin(1, Counter.T26());
		
		brregdir.setInputPin(0, Counter.T37());
		brregdir.setInputPin(1, Counter.T3D());
		
	}
	public static Pin bradr(){
		return Counter.T1A();
	}
	public static Pin bropr(){
		return Counter.T2D();
	}
	public static Pin brnotSTART(){
		return Counter.T00();
	}
	public static Pin brnotbrpom(){
		return Counter.T58();
	}
	public static Pin brnotprekid(){
		return Counter.T75();
	}
	public static Pin brnotPRINS(){
		return Counter.T82();
	}
	public static Pin brnotPRCOD(){
		return Counter.T84();
	}
	public static Pin brnotPRADR(){
		return Counter.T86();
	}
	public static Pin brnotPRINM(){
		return Counter.T88();
	}
	public static Pin brnotprintr(){
		return Counter.T8A();
	}
	public static Pin brnotgropr(){
		return Counter.T06();
	}
	public static Pin brI1(){
		return Counter.T08();
	}
	public static Pin brnotgradr(){
		return Counter.T0D();
	}
	public static Pin brI2_brnch(){
		return Counter.T0F();
	}
	public static Pin brI2_arlog(){
		return Counter.T10();
	}
	public static Pin brI3_jump(){
		return Counter.T14();
	}
	public static Pin brI3_arlog(){
		return Counter.T15();
	}
	public static Pin bruncnd(){
		return bruncnd.getOut(0);
	}
	public static Pin brcnd(){
		return brcnd.getOut(0);
	}
	public static Pin brnotbrqstop(){
		return brnotbrqstop.getOut(0);
	}
	public static Pin brstore(){
		return brstore.getOut(0);
	}
	public static Pin brLDW(){
		return brLDW.getOut(0);
	}
	public static Pin brregdir(){
		return brregdir.getOut(0);
	}
	
}
